### ISSUE TITLE
Validar registro de cliente em servidor

### ISSUE THREAD

**Issue by boidacarapreta** [smu20232/rpg#10]
Apresentar, no corpo desta tarefa, o registro do cliente no servidor. Pode ser a captura de tela do console do Javascript com as mensagens, depuração da aplicação ou outro mecanismo válido.

Depende de #8 e de #9.

**Comment by joaoonegri** [comment]
Registro validado, atualmente há apenas uma sala.

Log do servidor comprovando o registro:

```
Sep 14 03:00:52 PM  A client connected
Sep 14 03:00:59 PM  {
Sep 14 03:00:59 PM    Max: 1,
Sep 14 03:00:59 PM    To: '<sala1@rpg-3fg3.onrender.com>',
Sep 14 03:00:59 PM    From: '<joao.rn@aluno.ifsc.edu.br>',
Sep 14 03:00:59 PM    CallID: 'joao.rn@aluno.ifsc.edu.br1694714459451',
Sep 14 03:00:59 PM    Expires: '3600'
Sep 14 03:00:59 PM  }
Sep 14 03:00:59 PM  A client disconnected
```
