### ISSUE TITLE
Validar sessão de mídia multijogador

### ISSUE THREAD

**Issue by boidacarapreta** [smu20232/rpg#13]
Uma vez os clientes registrados no servidor (#8) com suporte a SDP (#12), eles devem estabelecer uma sessão válida de mídia entre os dois terminais. Usar captura de tela, console de Javascript, depuração da aplicação ou outro mecanismo válido para apresentar os canais de mídia estabelecidos em P2P.

**Comment by joaoonegri** [comment]
Finalizado no último commit, sessão de mídia para vídeo e áudio de N para N.
