### ISSUE TITLE
Validar estabelecimento de sessão de mídia com NAT

### ISSUE THREAD

**Issue by boidacarapreta** [smu20232/rpg#17]
Garantir que a mídia trafegará entre os dois clientes mesmo com NAT em um dos terminais. Ferramenta recomendada: [Trickle ICE](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/). Depende de #16.

**Comment by joaoonegri** [comment]
Validado, o problema era o uso de portas que estavam bloqueadas por padrão.
