### ISSUE TITLE
Fluxo de menus

### ISSUE THREAD

**Issue by mikeicd** [smu20232/rpg#30]

**Comment by MatheusDMedeiros** [comment]
# Fluxo de menus

## Inícial
![SMU_fluxo_jogo_01_Inicio](https://github.com/smu20232/rpg/assets/44479445/97b3465d-6718-475d-8a84-bccaa3d23d96)

## Jogador
![SMU_fluxo_jogo_02_Jogador](https://github.com/smu20232/rpg/assets/44479445/3e43b63f-bf60-444b-9624-db4a58b2e9eb)

## Mestre
![SMU_fluxo_jogo_03_Mestre](https://github.com/smu20232/rpg/assets/44479445/52f8e39e-6bba-471d-b91a-3c61cfd3e74b)
